name: Generate and Upload Content

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python generate_random_content.py

      - name: Set Git configuration
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and push changes
        run: |
          git add _posts/
          git commit -m "Add new random content" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/m-cochran/Randomerr.git HEAD:main
