name: Fetch Printful Products

on:
  schedule:
    - cron: '0 0 * * *' # Schedule to run daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-products:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get OAuth 2.0 Token
      id: get_token
      run: |
        response=$(curl -X POST "https://api.printful.com/oauth/token" \
            -d "grant_type=client_credentials" \
            -d "client_id=${{ secrets.PRINTFUL_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.PRINTFUL_CLIENT_SECRET }}")
        echo "response=$response"
        echo "::set-output name=token::$(echo $response | jq -r '.access_token')"

    - name: Fetch products from Printful API
      env:
        ACCESS_TOKEN: ${{ steps.get_token.outputs.token }}
      run: |
        curl -H "Authorization: Bearer $ACCESS_TOKEN" \
             https://api.printful.com/store/products \
             -o products.json

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add products.json
        git commit -m "Update products from Printful" || echo "No changes to commit"
        git push
