name: Fetch Printful Products

on:
  push:
    branches:
      - main  # Adjust this to your default branch if necessary

jobs:
  fetch-products:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch products from Printful API
        env:
          PRINTFUL_API_KEY: ${{ secrets.PRINTFUL_API_KEY }}
        run: |
          curl -X GET 'https://api.printful.com/store/products' \
          -H 'Authorization: Bearer l4PIbVit2m3wq1B6UuCzldKhsdgOlRjhCOh06UAR
               -o products.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add products.json
          git commit -m "Update products from Printful"
          git push
