name: Fetch Printful Products

on:
  schedule:
    - cron: '0 0 * * *' # Schedule to run daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-products:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get OAuth 2.0 Token
      id: get_token
      run: |
        response=$(curl -s -X POST "https://api.printful.com/oauth/token" \
            -d "grant_type=client_credentials" \
            -d "client_id=${{ secrets.PRINTFUL_CLIENT_ID }}" \
            -d "client_secret=${{ secrets.PRINTFUL_CLIENT_SECRET }}")
        
        # Check if the response contains an error
        if echo "$response" | jq -e '.error' > /dev/null; then
          echo "Error fetching OAuth token: $(echo $response | jq -r '.error.message')"
          exit 1
        fi
        
        # Extract and output the access token
        token=$(echo $response | jq -r '.access_token')
        if [ -z "$token" ] || [ "$token" == "null" ]; then
          echo "Failed to retrieve a valid OAuth token."
          exit 1
        fi
        
        echo "Successfully retrieved OAuth token."
        echo "::set-output name=token::$token"

    - name: Fetch products from Printful API
      env:
        ACCESS_TOKEN: ${{ steps.get_token.outputs.token }}
      run: |
        response=$(curl -s -H "Authorization: Bearer $ACCESS_TOKEN" \
                        https://api.printful.com/store/products)
        
        # Check if the response contains an error
        if echo "$response" | jq -e '.error' > /dev/null; then
          echo "Error fetching products: $(echo $response | jq -r '.error.message')"
          exit 1
        fi
        
        # Save the products to a JSON file
        echo $response | jq '.' > products.json
        echo "Successfully fetched and saved products."

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add products.json
        git commit -m "Update products from Printful" || echo "No changes to commit"
        git push
